config/routes.rb
Yycrebuild::Application.routes.draw do
  root :to => 'needs#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  resources :needs, :only => [:index, :show, :create]
  resources :neighbourhoods, :only => [:index]
  resources :resources
  resources :links, :only => [:index, :create], :path => :l
  resources :tags, :only => [:show], :path => :t
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/geo_location_service.rb
# A service that can look up a geo-location from a string
# the api this is based on (ERSI) seems fairly robust and can
# take landmarks (Stampede Grounds) and street addresses.

# work by Chris Desmarais (codeshoulders@gmail.com)

require 'rest_client'
require 'open-uri'
require 'json'

class GeoLocationService

	def self.GetGeoLocation( locationString)
		return ExtractGeoLocationFromJson( GetGeoLocationData( locationString ) )
	end

	def self.GetGeoLocationData(locationString)
		urlAsString =  "http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?f=pjson&text="
		urlAsString += URI::encode(locationString)
		return RestClient.get urlAsString	
	end
	
	def self.ExtractGeoLocationFromJson( jsonString)
		parsed = JSON.parse(jsonString)
		
                return nil if parsed["locations"].length == 0
                
		# need to handle more than one match
		x = parsed["locations"][0]["feature"]["geometry"]["x"]
		y = parsed["locations"][0]["feature"]["geometry"]["y"]
		return GeoLocation.new( x, y)
	end
end

class GeoLocation
	attr_accessor :x, :y
	def initialize (x,y)
		@x = x
		@y = y
	end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url, :description, :title, :thumbnail_url
  validates :url,  :presence => true
  belongs_to :user
  acts_as_taggable

  default_scope order("created_at DESC")

  def to_param
    "#{id}-#{heading.gsub(/[^a-z0-9]+/i, '-')}"
  end 
end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :address, :latitude, :longitude
  acts_as_taggable
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  default_scope order("created_at DESC")
end

app/models/neighbourhood.rb
class Neighbourhood < ActiveRecord::Base
  attr_accessible :name, :status
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  after_save :get_location

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :postal_code, :latitude, :longitude
  has_many :needs
  has_many :links
  acts_as_tagger

private

  def get_location

    return if self.postal_code.nil? 
  
    location = GeoLocationService.GetGeoLocation(self.postal_code)

    return if location.nil?

    update_column :latitude, location.y
    update_column :longitude, location.x
    
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authenticate_user!, :except => [:index]

  def index
    @links = Link.all
  end

  def create
    @link = current_user.links.create(:url => CGI.unescape(params[:url]), :title => CGI.unescape(params[:title]), :description => CGI.unescape(params[:description]), :thumbnail_url => CGI.unescape(params[:thumbnail_url]))
    redirect_to links_path
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  def index
    @needs = Need.all
    @tags = ActsAsTaggableOn::Tag.pluck(:name)
  end

  def show
    @need = Need.find(params[:id])
  end

  def create
    @need = current_user.needs.create(params[:need])
    current_user.tag(@need, :with => params[:need_tags], :on => :tags)
    if @need.save
      redirect_to needs_path, notice: 'Need was successfully created.'
    else
      render action: "new"
    end
  end
end

app/controllers/neighbourhoods_controller.rb
class NeighbourhoodsController < ApplicationController
  def index
    @neighbourhoods = Neighbourhood.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = params[:id]
    @needs = Need.tagged_with(@tag)
  end
end

app/helpers/GeoLocationService/GeoLocationService.rb
# A service that can look up a geo-location from a string
# the api this is based on (ERSI) seems fairly robust and can
# take landmarks (Stampede Grounds) and street addresses.

# work by Chris Desmarais (codeshoulders@gmail.com)

require 'rest_client'
require 'open-uri'
require 'json'

class GeoLocationService

	def self.GetGeoLocation( locationString)
		return ExtractGeoLocationFromJson( GetGeoLocationData( locationString ) )
	end

	def self.GetGeoLocationData(locationString)
		urlAsString =  "http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?f=pjson&text="
		urlAsString += URI::encode(locationString)
		return RestClient.get urlAsString	
	end
	
	def self.ExtractGeoLocationFromJson( jsonString)
		parsed = JSON.parse(jsonString)
		
		# need to handle more than one match
		x = parsed["locations"][0]["feature"]["geometry"]["x"]
		y = parsed["locations"][0]["feature"]["geometry"]["y"]
		return GeoLocation.new( x, y)
	end
end

class GeoLocation

	attr_accessor :x, :y
	
	def initialize (x,y)
		@x = x
		@y = y
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 40 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    image_tag("https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{options[:size]}&d=mm", alt: user.name, class: 'gravatar')
  end
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/neighbourhoods_helper.rb
module NeighbourhoodsHelper
  def css_class_for(neighbourhood)
    case
    when neighbourhood.status.start_with?('Evac')
      "evac"
    when neighbourhood.status.start_with?('Part')
      "part"
    else
      "open"
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="hidden-phone">
<div class="container">
  <div class="row">
    <div class="span12"></div>
  </div>
</div>		
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Rebuild YYC</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Needs", needs_path %></li>
          <li><%= link_to "Neighbourhoods", neighbourhoods_path %></li>
          <li><a href="http://t.co/exF4flyIPd" target="_blank">Map</a></li>
          <li><%= link_to "News", links_path %></li>
        </ul>
        <ul class="nav pull-right">
          <li><a href="http://github.com/mokhan/yycrebuild">Developers <i class="icon-github"></i></a> </li>
          <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.email %> <i class="icon-gear"></i><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li> <%= link_to "Settings", edit_user_registration_path %> </li>
                <li class="divider"></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
          <% else %>
            <li> <a href="<%= url_for new_user_session_path %>">Sign In</a> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="span12">
    <% if(flash.any?) -%>
      <% flash.each do |key, value| -%>
        <% Array(value).uniq.each do |message| -%>
          <div class="alert alert-<%= key %>">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <%= message %>
          </div>
        <% end -%>
      <% end -%>
    <% end -%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>YYC Rebuild</title>
    <%= stylesheet_link_tag :application %>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <%= yield :head %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div> <!-- /container -->
    <%= render "layouts/footer" %>
    <%= javascript_include_tag :application %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= yield :javascript %>
  </body>
</html>

app/views/links/index.html.erb
<% content_for :javascript do %>
<script src="http://cdn.embed.ly/jquery.embedly-3.0.5.min.js" type="text/javascript"></script>
<script src="http://cdn.embed.ly/jquery.preview-0.3.2.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="http://cdn.embed.ly/jquery.preview-0.3.2.css" />
<script>
$('#url').preview({ key:'<%= ENV['EMBEDLY_KEY']  %>' });
$('form').on('submit', function(){
  $(this).addInputs($('#url').data('preview'));
  return true;
});
</script>
<% end %>

<div class="row">
  <div class="span12">
    <% if user_signed_in? %>
      <%= form_for Link.new, :url => links_path, :method => :post, :html => { :class => "form-inline" } do |f| %>
        <input type="text" id="url" name="url" value="" placeholder="http://google.com/" />
        <%= f.submit :add, :class => "btn" %>
        <div class="selector-wrapper"></div>
      <% end %>
    <% else %>
      <%= link_to "Add Link", new_user_session_path %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="span12">
    <table class="table">
      <tr>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @links.each do |link| %>
        <tr>
        <td><%= image_tag link.thumbnail_url %></td>
        <td><%= link_to link.title, link.url %></td>
        <td><%= link.description %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/needs/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript" charset="utf-8">
$(function() {
  $('#tags').tagit({ availableTags: [<% @tags.each { |x| %>'<%= x %>',<% } %>] });
});
</script>
<% end %>
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">

<div class="row">
  <div class="span5">
    <% if user_signed_in? %>
      <h1>I need...</h1>
      <%= form_for Need.new, :html => {:class => "form-inline"} do |f| %>
        <div class="control-group">
        <div class="controls">
          <%= f.text_area :description, cols: 160, rows: 2, :class => "span5" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :address, :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :address %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="tags">Tags</label>
        <div class="controls">
          <input name="need_tags" type="text" id="tags" value="" class="input-xxlarge" autocomplete="off" placeholder="e.g. trucks, sunnyside" />
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Send", :class => "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <%= link_to "I need...", new_user_registration_path, :class => "btn btn-primary" %>
  <% end %>
    <h2>Recently needed:</h2>
    <table class="table">
      <% @needs.each do |need| %>
        <tr>
        <td><%= gravatar_for(need.user) %></td> 
        <td><%= need.user.name %></td>
        <td> I need <%= need.description %>
        <span> <i class="icon-tags"></i> </span>
          <% need.tags.each do |tag| -%>
            <a href="<%= url_for tag_path(tag.name) %>"><span class="label"><%= tag.name %></span></a>
        <% end -%>
        </td>
        <td><%= link_to "Help", need_path(need), :class => "btn" %></td>
      </tr>
    <% end %>
    </table>
  </div>
  <div class="span5">
    <h1>I have...</h1>
  </div>
  <div class="span2">
    <h2>Updates</h2>
    <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/search?q=%23yycflood"  data-widget-id="348909521470648320">Tweets about "#yycflood"</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
</div>

app/views/needs/show.html.erb
<div class="row">
  <div class="span6">
    <p>My name is <%= @need.user.name %> and I need...</p>
    <p class="lead"><%= @need.description %></p>
  </div>
  <div class="span6">
    <p>You can contact me by <%= mail_to @need.user.email, "email", :encode => "javascript" %>.</p>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@need.latitude}%2C#{@need.longitude}" %>
  </div>
</div>

<div class="row">
  <div class="span12">
  <div id="disqus_thread"></div>
  <script type="text/javascript">
var disqus_shortname = 'rebuildyyc';
var disqus_identifier = "need-<%= @need.id %>";
(function() {
  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
  dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
  </div>
</div>

app/views/neighbourhoods/index.html.erb
<div class="row neighbourhoods">
  <div class="span12">
    <h1>Neighbourhoods</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
      <% @neighbourhoods.sort { |a,b| a.name <=> b.name }.each do |neighbourhood| %>
      <tr>
        <td><%= neighbourhood.name %></td>
        <td class="<%= css_class_for(neighbourhood) %>"><%= neighbourhood.status %></td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tags/show.html.erb
<div class="row">
  <div class="span12">
    <table class="table">
      <tr>
        <th></th>
        <th></th>
        <th>Need</th>
        <th>Tags</th>
        <th></th>
      </tr>
      <% @needs.each do |need| %>
      <tr>
        <td><%= gravatar_for(need.user) %></td> 
        <td><%= need.user.name %></td>
        <td> I need <%= need.description %></td>
        <td><span> <i class="icon-tags"></i> </span>
        <% need.tags.each do |tag| -%>
          <a href="<%= url_for tag_path(tag.name) %>"><span class="label"><%= tag.name %></span></a>
        <% end -%>
        </td>
        <td><%= link_to "Help", need_path(need), :class => "btn" %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>